# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: ec9df5b913bc748f2966ce6f08cc3a86bf3089e25a731b09aa2969a300fad766a62c0909db3b64a0e09b7684876d796963a4946c72ffa4a2a64859181772a07f

test:
  secret_key_base: 5016839a904df31a652d35273cd300c526255039c3d60319250b0fc481e8d00b100cb6c9cdd8547e5e3dfee2d97282f635310286f4eaac291440024b6becca44

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
